char* names[] = {
	"Livra Cotton",
	"Laribald Hemp",
	"Carlyne Flax",
	"Iron Ore",
	"Mythril Ore",
	"Gold Ore",
	"Petrified Log",
	"Hardwood",
	"Sacred Branch",
	"Rope Scrap",
	"Small Compass",
	"Fur Weave",
	"Coarse Silica",
	"Copper Silksand",
	"Auric Sand",
	"Chacker Nut",
	"Amostran Coconut",
	"Lillium Pawpaw",
	"Bird Bone",
	"Animal Bone",
	"Beast Bone",
	"Sunlight Dew",
	"Magic Droplet",
	"Holy Water Bead",
	"Subdued Prism",
	"Cloudless Prism",
	"Radiant Prism",
	"Knight Guide",
	"Monk Guide",
	"Ranger Guide",
	"Dark Knight Guide",
	"Paladin Guide",
	"Dragoon Guide",
	"Ninja Guide",
	"Samurai Guide",
	"White Mage Guide",
	"Black Mage Guide",
	"Time Mage Guide",
	"Sage Guide",
	"Red Mage Guide",
	"Blue Mage Guide",
	"Thief Guide",
	"Beastmaster Guide",
	"Bard Guide",
	"Machinist Guide",
	"Geomancer Guide",
	"Alchemist Guide",
	"Fire Prismite",
	"Water Prismite",
	"Wind Prismite",
	"Earth Prismite",
	"Fire Magethyst",
	"Water Magethyst",
	"Wind Magethyst",
	"Earth Magethyst",
	"Rusted Iron Scrap",
	"Hardened Bone",
	"Small Feather",
	"Sharp Fang",
	"Heavy Carapace",
	"Tanned Hide",
	"Blue Liquid",
	"Carrion Ash",
	"Sturdy Vine",
	"Magic Source",
	"Blazing Magethyst",
	"Diluvial Magethyst",
	"Howling Magethyst",
	"Seismic Magethyst",
	"Spellcast Iron",
	"Large Bone",
	"Large Feather",
	"Vicious Fang",
	"Prism Carapace",
	"Prime Tanned Hide",
	"Silver Liquid",
	"Gleaming Ash",
	"Stinky Vine",
	"Astral Source",
	"Crimson Talon",
	"Fire Tertial",
	"Dayring Stone",
	"Fulmicite",
	"Nightmare Figment",
	"Ethereal Dragonclaw",
	"Frigid Kiss",
	"Lone Wolf's Soul",
	"Deepwater Quill",
	"Seduction Powder",
	"Sacred Device",
	"Eiherjar Soul",
	"Goblin Horn",
	"Goblin Guard's Belt",
	"Goblin Lord's Jewel",
	"Bomb Fragment",
	"Mom Bomb Core",
	"Chocobo Feather",
	"---",
	"---",
	"Vulture Sight",
	"Helldiver Pinion",
	"Cockatrice Talon",
	"Toad Oil",
	"Grandtoad Hasma",
	"Lamia Oculus",
	"Medusa Glare",
	"Mandragora Leaf",
	"Alraune Root",
	"Malboro Tentacle",
	"Malboro Eyeball",
	"Forfex Shell",
	"Attacker Claw",
	"Land Turtle Shell",
	"Gil Snapper Shell",
	"Adamantite",
	"Pink Tail",
	"Flan Gel",
	"Ghost Tatter",
	"Specter Leather",
	"Floating Eyeball",
	"Fiendish Eyeball",
	"Demon Wing",
	"Belial Tail",
	"Devil Horn",
	"Lizard Leather",
	"Basilisk Slough",
	"Firedrake Scale",
	"Icedrake Talon",
	"Earthdrake Fang",
	"Mordrake Bone",
	"Coeurl Claw",
	"Sabertooth Pelt",
	"Behemoth Horn",
	"Behemoth King Horn",
	"Iron Giant Alloy",
	"Wolframitan Gilhorn",
	"Centaurion Plate",
	"Black Knight Plate",
	"Skeleton Skull",
	"Death Knight Skull",
	"Lich's Skull",
	"Bat Wing",
	"Vampyr Sanguinite",
	"Karmic Lantern",
	"Royal Crown",
	"Cactuar Needle",
	"Gigantuar Needle",
	"Magic Pot Shard",
	"Hellish Bauble",
	"Immolated Hide",
	"Hellish Horn",
	"Hellish Bracer",
	"Tenebrous Horn",
	"Nightweep Bead",
	"Tenebrous Wing",
	"Tenebrous Tailspine",
	"Crackling Vestment",
	"Shattered Levin",
	"Crackling Sash",
	"Crackling Prism",
	"Gelid Diamond",
	"Argent Fabric",
	"Gelid Silverband",
	"Gelid Chain",
	"Thalassic Scale",
	"Tidal Undulation",
	"Thalassic Horn",
	"Thalassic Fin",
	"Thalassic Tail",
	"Bewitching Pollen",
	"Succulent Nectar",
	"Bewitching Petal",
	"Bewitching Bath",
	"Bewitching Infusion",
	"Ireful Sigil",
	"Warlord Plate",
	"Ireful Helmhorn",
	"Ireful CLoak",
	"Ireful Harness",
	"Revenant Fire",
	"Solar Firedust",
	"Revenant Wing",
	"Revenant Tailfeather",
	"Crystalline Scale",
	"Cerulean Prism",
	"Crystalline Core",
	"Crystalline Blade",
	"Crystalline Spine",
	"Inviolable Circuit",
	"Bastion Stone",
	"Inviolable Panel",
	"Inviolable Sprocket",
	"Selenic Prism",
	"Moonlight Droplet",
	"Selenic Fang",
	"Selenic Pelt",
	"Selenic Tail",
	"Daybreak Robe",
	"Photic Scute",
	"Daybreak Mask",
	"Daybreak Shard",
	"Genji Crest",
	"Warrior Sigil",
	"Genji Cowl",
	"Genji Sash",
	"Achilles Heel",
	"Omega Badge",
	"Omega Armor",
	"Omega Circuit (alpha)",
	"Omega Circuit (Omega)",
	"Omega Antenna",
	"Geotic Memory",
	"Crimson Geode",
	"Azure Geode",
	"Verdant Geode",
	"Gleaming Geode",
	"Umbral Geode",
	"Crimson Geocrux",
	"Azure Geocrux",
	"Verdant Geocrux",
	"Gleaming Geocrux",
	"Umbral Geocrux",
	"Infernal Jewel",
	"Infernal Gouge",
	"Infernal Shackle",
	"Atramental Crown",
	"Atramental Eclipser",
	"Atramental Tailspike",
	"Fulminant Raiment",
	"Fulminant Girdle",
	"Fulminant Jadeshard",
	"Icetouched Zuredian",
	"Icetouched Goldband",
	"Icetouched Fetters",
	"Pelagic Weave",
	"Pelagic Driver",
	"Pelagic Grandfin",
	"Pelagic Grandtail",
	"Numinous Allergen",
	"Numinous Blossom",
	"Numinous Alkahest",
	"Numinous Tincture",
	"Inimical Crest",
	"Inimical Silverhorn",
	"Inimical Greatcoat",
	"Inimical Goldbridle",
	"Conflagrant Torrent",
	"Conflagrant Pennon",
	"Conflagrant Vane",
	"Omnipotent Lamina",
	"Omnipotent Nexus",
	"Omnipotent Razor",
	"Omnipotent Spike",
	"Sacrosanct Network",
	"Sacrosanct Armor",
	"Sacrosanct Widget",
	"Lunatic Silvercryst",
	"Lunatic Tusk",
	"Lunatic Ironhide",
	"Lunatic Pendulum",
	"Sunbeam Raiment",
	"Sunbeam Visage",
	"Sunbeam Mirror",
	"Squishy Cotton",
	"Gilflax Seed",
	"Damascus Ore",
	"Orichalcum Ore",
	"Aquilaria Log",
	"Divine Log",
	"Thick Canvas",
	"Explorer's Diary",
	"Emery Powder",
	"Demention Sands",
	"Mockmoon Berry",
	"Woll Fruit",
	"Grand Beastbone",
	"Avatar Backbone",
	"Faerie Droplet",
	"Spirit Droplet",
	"Yggra Prism",
	"Eternal Prism",
	"Knuckle Schema",
	"Sword Schema",
	"Dagger Schema",
	"Katana Schema",
	"Ninjato Schema",
	"Spear Schema",
	"Axe Schema",
	"Scythe Schema",
	"Club Schema",
	"Bell Schema",
	"Staff Schema",
	"Bow Schema",
	"Firearm Schema",
	"Artillery Schema",
	"Instrument Schema",
	"Rod Schema",
	"Tome Schema",
	"Buckler Schema",
	"Pavis Schema",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"---",
	"Light Crystal",
	"Gold Choco Feather",
	"Stiltzkin's Diary",
	"SOLDIER's Pride",
	"Dragoon Lore",
	"Mark of Destiny",
	"Jenova Cells",
	"Phantoma",
	"Savior's Wish",
	"Model Gun",
	"Ruined Relic",
	"Toolbox"
};
